version: '3.8'
services:
  jenkins_agent_gradle:
    image: jvalentino2/jenkins-agent-gradle
    privileged: true
    user: root
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jenkins_agent_gradle
    volumes:
     - ./workspace:/home/jenkins/workspace
